version: '3.0'
volumes:
   rapid-mongo-db:
   rapid-postgres-db:
services:
  web:
    image: "digitaldrummerj/angular-cli"
    ports:
      - "4200:4200"
      - "49153:49153"
      - "9222:9222"
      - "9876:9876"
    depends_on:
      - "sails"
    working_dir: /home/app
    links:
      - "sails"
    volumes:
      - ./frontend:/home/app
    command: "ng serve --host 0.0.0.0 --port 4200 --poll "
    environment:
      - NODE_ENV=dev
  sails:
    image: "digitaldrummerj/sails"
    ports:
     - "1337:1337"
     - "9229:9229"
    depends_on:
       - "rapid-postgres"
       - "mongo"
    links:
       - "rapid-postgres"
       - "mongo"
    volumes:
        - ./backend:/home/app
    command: ["sails", "lift"]
    environment:
       - NODE_ENV=dev
  rapid-postgres:
    image: "rapid-postgres"
    ports:
      - "5432:5432"
    volumes:
       - rapid-postgres-db:/data
    environment:
      - PGDATA=/data
      - POSTGRES_USER=sails
      - POSTGRES_PASSWORD=sails
      - POSTGRES_DB=sails
  mongo:
     ports:
       - "27017:27017"
     image: "mongo"
     volumes: 
       - rapid-mongo-db:/data/db
       - rapid-mongo-db:/data/configdb
