version: '3.0'
services:
  web:
    image: "digitaldrummerj/angular-cli"
    ports:
      - "4200:4200"
      - "49153:49153"
      - "9222:9222"
      - "9876:9876"
    links:
      - "sails"
    volumes:
      - ./frontend:/home/app
    restart: always
    environment:
      - NODE_ENV=dev
    network_mode: "default"
  sails:
    image: "digitaldrummerj/sails"
    ports:
     - "1337:1337"
    links:
       - "postgres"
       - "mongo"
    volumes:
        - ./backend:/home/app
    command: ["sails", "lift"]
    restart: always
    environment:
       - NODE_ENV=dev
    network_mode: "default"
  postgres:
    image: "postgres"
    restart: always

    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=sails
    network_mode: "default"
  mongo:
     ports:
      - "27017:27017"
     image: "mongo"
     restart: always
     network_mode: "default"
